services:
    marcovo.hideBBcode.listener:
        class: marcovo\hideBBcode\event\listener
        arguments:
            - @dbal.conn
            - @user
            - @template
            - @config
            - @controller.helper
        tags:
            - { name: event.listener }
